linux:
  hosts:
    monitoringctrl:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ control_plane_ip }}"
    monitoringwrkr0:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[0] }}"
    monitoringwrkr1:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[1] }}"
    monitoringwrkr2:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[2] }}"
    monitoringwrkr3:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[3] }}"
    #monitoringwrkr4:
    #  ansible_user: "{{ ssh_user }}"
    #  ansible_host: "{{ worker_ips[4] }}"

vms:
  hosts:
    monitoringctrl:
    monitoringwrkr0:
    monitoringwrkr1:
    monitoringwrkr2:
    monitoringwrkr3:
    #monitoringwrkr4:

controllers:
  hosts:
    monitoringctrl:
  
workers:
  hosts:
    monitoringwrkr0:
    monitoringwrkr1:
    monitoringwrkr2:
    monitoringwrkr3:
    #monitoringwrkr4: